'use client';

import { useMemo } from 'react';

const tips = [
  // Performance & Optimization (1-50)
  'Update your GPU drivers regularly to avoid stutters and performance issues.',
  'Close background apps before launching your game to free up RAM and CPU.',
  'Lower your resolution scale slightly for smoother frames without sacrificing much quality.',
  'Use borderless windowed mode to alt-tab faster between applications.',
  'Enable XMP/EXPO in BIOS to run your RAM at its rated speed.',
  'Check CPU temperatures - thermal throttling can cause FPS drops.',
  'Disable Windows Game DVR to reduce background recording overhead.',
  'Clean your PC fans and heatsinks every 3-6 months for better cooling.',
  'Cap your FPS to your monitor refresh rate to reduce input lag.',
  'Use high performance power plan in Windows for maximum CPU performance.',
  'Disable fullscreen optimizations in game .exe properties for better performance.',
  'Update your motherboard BIOS for improved CPU and RAM stability.',
  'Close Chrome or Edge when gaming - browsers use lots of RAM.',
  'Overclock your GPU carefully to squeeze out extra FPS.',
  'Use MSI Afterburner to monitor temps and FPS in-game.',
  'Disable unnecessary startup programs to speed up boot times.',
  'Defragment your HDD monthly (skip this for SSDs).',
  'Install games on an SSD for faster load times.',
  'Use Game Mode in Windows 11 to prioritize gaming performance.',
  'Check for Windows updates - they often include performance fixes.',
  'Turn off V-Sync if you have a high refresh rate monitor.',
  'Lower shadow quality first - it has the biggest performance impact.',
  'Disable motion blur for clearer visuals and better responsiveness.',
  'Use DLSS or FSR to boost FPS while maintaining visual quality.',
  'Keep your GPU at 70-80°C max under load for longevity.',
  'Upgrade to 16GB RAM minimum for modern gaming.',
  'Use separate SSDs for OS and games for better performance.',
  'Check your GPU usage - 95-99% means your GPU is the bottleneck.',
  'Monitor CPU usage per core to identify single-thread bottlenecks.',
  'Use Display Driver Uninstaller (DDU) when updating GPU drivers.',
  'Disable in-game overlays from Discord, GeForce Experience, etc. for FPS gains.',
  'Lower anti-aliasing settings for instant FPS boost with minimal visual loss.',
  'Use low latency mode in NVIDIA Control Panel for better responsiveness.',
  'Check your RAM speed in Task Manager - it should match your rated speed.',
  'Unpark CPU cores for better multi-threaded performance.',
  'Disable Superfetch/SysMain service if you have an SSD.',
  'Use Process Lasso to prevent background tasks from hogging CPU.',
  'Clean install GPU drivers every 6 months to avoid driver bloat.',
  'Check your monitor cable - DisplayPort 1.4+ for high refresh rates.',
  'Enable Resizable BAR in BIOS for up to 10% more FPS on modern GPUs.',
  'Use custom fan curves to keep temps low without excessive noise.',
  'Disable Windows Search indexing on your game drive.',
  'Lower texture quality if you have less than 8GB VRAM.',
  'Use NVIDIA Reflex or AMD Anti-Lag for reduced input lag in competitive games.',
  'Check your RAM is installed in dual-channel mode (slots 2 and 4).',
  'Limit background downloads when gaming to avoid ping spikes.',
  'Use a wired Ethernet connection instead of WiFi for lower latency.',
  'Undervolt your GPU to reduce temps and power draw without losing performance.',
  'Check your SSD health with CrystalDiskInfo every few months.',
  'Use task manager to check which programs are using your disk at 100%.',

  // Hardware & Upgrades (51-100)
  'The CPU matters more at 1080p - GPU matters more at 4K.',
  'X3D CPUs from AMD are the best for gaming due to extra cache.',
  'Mid-range GPUs offer the best price-to-performance ratio.',
  'Faster RAM significantly boosts FPS on AMD Ryzen CPUs.',
  'A good CPU cooler can add years to your processor\'s lifespan.',
  'Quality power supplies have 80+ Gold or Platinum ratings.',
  'NVMe Gen 4 SSDs are overkill for gaming - Gen 3 is fine.',
  'Don\'t cheap out on your motherboard - VRMs matter for overclocking.',
  'Higher wattage PSU doesn\'t mean higher power consumption.',
  'Case airflow matters more than RGB fans.',
  'Adaptive sync (G-Sync/FreeSync) eliminates screen tearing.',
  '1% lows matter more than average FPS for smooth gameplay.',
  'More VRAM is essential for high-res textures and ray tracing.',
  'CPU bottlenecks are more noticeable at lower resolutions.',
  'ITX builds look great but can run hotter - plan cooling carefully.',
  'Buy the best GPU you can afford - easiest upgrade for FPS.',
  'Wait for new GPU launches - prices drop on previous gen cards.',
  'Check PCPartPicker for compatibility before buying components.',
  'Benchmark your PC on OptiPlay to compare with similar builds.',
  'Your mouse matters - get one with a good sensor like PixArt 3395.',
  'Low polling rate mice add input lag - use 1000Hz minimum.',
  '144Hz monitors are the sweet spot for competitive gaming.',
  'IPS panels have better colors, TN has faster response times.',
  'Curved monitors reduce eye strain for long gaming sessions.',
  '1440p 165Hz is the best balance for modern gaming.',
  'Check your motherboard QVL list before buying RAM.',
  'DDR5 is expensive - DDR4 is still great for gaming.',
  'RGB adds no performance but looks awesome.',
  'Cable management improves airflow and aesthetics.',
  'Thermal paste needs replacing every 2-3 years.',
  'Arctic MX-5 and Noctua NT-H2 are top-tier thermal pastes.',
  'All-in-one liquid coolers need less maintenance than custom loops.',
  'Mesh front panel cases have better airflow than solid glass.',
  'Negative air pressure pulls in dust - aim for positive pressure.',
  'Your GPU should be in the top PCIe slot for best performance.',
  'SLI and Crossfire are dead - single GPU is the way.',
  'Reference GPU coolers are louder - aftermarket models run cooler.',
  'Buy at least 750W PSU for high-end GPUs like RTX 4080/4090.',
  'Modular PSUs make cable management much easier.',
  'Backplates on GPUs help with cooling and rigidity.',
  'RGB can be controlled through software like OpenRGB or SignalRGB.',
  'Don\'t mix RAM kits - buy a matched set for stability.',
  'B-die Samsung RAM overclocks the best but is pricey.',
  'PCIe 4.0 matters for GPUs - Gen 3 can bottleneck high-end cards.',
  'Use custom PCIe power cables - don\'t daisy chain on high-end GPUs.',
  'GPU sag can damage your PCIe slot over time - use a support bracket.',
  'Water cooling is quieter but more expensive than air cooling.',
  'Noctua NH-D15 is the best air cooler for high-end CPUs.',
  'Check your motherboard supports your CPU - BIOS updates may be needed.',
  'Watch for GPU coil whine - it\'s annoying but not dangerous.',

  // In-Game Settings (101-150)
  'Competitive players use low settings for max FPS and clarity.',
  'Turn off depth of field - it blurs your vision in shooters.',
  'Ambient occlusion looks nice but costs 5-10 FPS.',
  'Use TAA for modern games - FXAA is outdated.',
  'Ray tracing looks amazing but cuts FPS in half without DLSS.',
  'DLSS Quality mode is the best balance of FPS and visuals.',
  'FSR works on any GPU but DLSS looks better on RTX cards.',
  'Lower your FOV slightly for better FPS in demanding games.',
  'Disable chromatic aberration - it just makes edges blurry.',
  'Use low or medium effects - explosions tank FPS in fights.',
  'Film grain should always be disabled - it adds ugly noise.',
  'Dynamic resolution can help maintain FPS but looks inconsistent.',
  'Volumetric lighting kills FPS - lower it first in optimization.',
  'Post-processing has minimal visual impact - turn it down for FPS.',
  'Use native resolution - lower res looks blurry on modern monitors.',
  'MSAA is expensive - use TAA or DLAA instead.',
  'Screen space reflections are cheaper than ray traced ones.',
  'Lower view distance in open-world games for big FPS gains.',
  'Use medium textures if you have 6GB VRAM or less.',
  'Anisotropic filtering at 16x has almost no performance cost.',
  'Check OptiPlay\'s benchmark page for optimal settings per game.',
  'Particle effects can cause stuttering in heavy fights.',
  'Use low grass density in games like PUBG or Fortnite.',
  'Shadows at medium look 90% as good as ultra for half the cost.',
  'Tessellation can crush older GPUs - turn it down.',
  'Global illumination is beautiful but very demanding.',
  'Use performance overlays to see which settings impact FPS most.',
  'Competitive games favor FPS - turn everything low.',
  'Single-player games can prioritize visuals over FPS.',
  'Cap FPS to 60 in menus to save power and heat.',

  // Network & Latency (151-180)
  'Check your ping with OptiPlay\'s heatmap tool.',
  'Use Cloudflare DNS (1.1.1.1) for faster DNS resolution.',
  'Restart your router weekly to clear memory leaks.',
  'Ethernet cables should be Cat6 or higher for gigabit speeds.',
  'QoS settings in your router can prioritize gaming traffic.',
  'Close torrent clients and downloads when gaming online.',
  'Packet loss is worse than high ping - check with ping tests.',
  'Use a VPN only if needed - it usually increases latency.',
  'Gaming routers with QoS help reduce lag in busy networks.',
  'WiFi 6E reduces latency compared to older WiFi standards.',
  'Position your router centrally for better WiFi coverage.',
  '5GHz WiFi is faster but shorter range than 2.4GHz.',
  'Bufferbloat causes lag spikes - test at dslreports.com/speedtest.',
  'Disable Windows Update P2P sharing to save bandwidth.',
  'Use server regions closest to you for lowest ping.',
  'Wired always beats wireless for competitive gaming.',
  'Mesh WiFi systems improve coverage in large homes.',
  'Update router firmware for security and performance.',
  'Powerline adapters are better than WiFi for gaming.',
  'Gaming on WiFi? Use 5GHz band for lower latency.',
  'Check if your ISP has throttling during peak hours.',
  'Discord voice can cause lag - lower quality if needed.',
  'Mumble has lower latency than Discord for voice.',
  'Use ExitLag or similar if your ISP routes poorly to game servers.',
  'Fiber internet has lower latency than cable or DSL.',
  'Check your upload speed - streaming needs at least 5-10 Mbps.',
  'High ping in specific games? Check for server outages.',
  'Use Task Manager to see which apps are using bandwidth.',
  'Your router might need an upgrade if it\'s over 5 years old.',
  'Gaming traffic is tiny - 100 Mbps is plenty for online play.',

  // Peripherals & Setup (181-220)
  'Lower your mouse DPI and increase in-game sensitivity for precision.',
  '400-800 DPI is optimal for most FPS players.',
  'Disable mouse acceleration for consistent aim.',
  'Use a large mousepad for low sensitivity arm aiming.',
  'Mechanical keyboards feel better but don\'t improve performance.',
  'Linear switches are popular for gaming - no tactile bump.',
  'Your monitor should be at eye level to reduce neck strain.',
  'Sit arm\'s length from your monitor for best viewing.',
  'Use 100% scaling in Windows - higher scaling can blur games.',
  'Blue light filters reduce eye strain during long sessions.',
  'Take 20-second breaks every 20 minutes to rest your eyes.',
  'Good posture prevents back pain during long gaming sessions.',
  'Invest in a quality chair - you sit in it for hours.',
  'Noise-canceling headphones help with immersion.',
  'Open-back headphones have better soundstage than closed-back.',
  'Separate mic and headphones often beat gaming headsets.',
  'XLR mics sound better but need an audio interface.',
  'USB mics like Blue Yeti are great for streaming on a budget.',
  'Use push-to-talk to avoid background noise in voice chat.',
  'Your desk height should let your elbows rest at 90 degrees.',
  'Cable management under your desk reduces clutter.',
  'Footrests help with posture if your chair is too high.',
  'Dual monitors improve productivity but can distract in games.',
  'Second monitor? Use it for Discord, browser, or streams.',
  'Clean your mousepad monthly for consistent glide.',
  'Replace mouse feet when they wear down for smooth gliding.',
  'Artisan mousepads are fast - control pads are slower but precise.',
  'Hard mousepads are durable but less comfortable than cloth.',
  'RGB lighting can cause distractions - keep it subtle.',
  'Bias lighting behind your monitor reduces eye strain.',
  'Keep drinks away from your keyboard - spills kill electronics.',
  'Keyboard wrist rests can help with comfort.',
  'TKL keyboards save desk space for your mousepad.',
  'Custom keycaps are fun but won\'t improve your gameplay.',
  'Lubed switches feel smoother and sound better.',
  'Hotswap keyboards let you change switches without soldering.',
  'Monitor arms free up desk space and improve ergonomics.',
  'Acoustic foam panels reduce echo in your streaming setup.',
  'Ring lights improve webcam quality for streaming.',
  'Use OBS for streaming - it\'s free and powerful.',

  // Software & Tools (221-260)
  'Use OptiPlay\'s PC Checker to see if you can run a game.',
  'Check OptiPlay benchmarks before buying new hardware.',
  'Use OptiPlay\'s crosshair generator for Valorant and CS2.',
  'HWInfo64 shows detailed temps, voltages, and clock speeds.',
  'MSI Afterburner lets you overclock and monitor in real-time.',
  'Use DDU (Display Driver Uninstaller) before installing new GPU drivers.',
  'CrystalDiskMark tests your SSD speed.',
  'UserBenchmark is useful but take results with a grain of salt.',
  'GeForce Experience optimizes game settings automatically.',
  'AMD Software does the same for Radeon GPUs.',
  'Use RTSS (RivaTuner) for more accurate FPS limiting.',
  'Process Lasso prevents background tasks from stealing CPU time.',
  'Disable Cortana and Windows Search to save RAM.',
  'Use Windows Debloater scripts to remove preinstalled junk.',
  'Timer Resolution tool can reduce input lag slightly.',
  'ISLC (Intelligent Standby List Cleaner) can help with RAM management.',
  'Windows 10 LTSC has no bloat but is harder to get.',
  'Use Ninite to install essential software quickly.',
  'CCleaner can help but be careful - it can break things if misused.',
  'Malwarebytes is good for occasional scans.',
  'Windows Defender is good enough - paid antivirus often slows PCs.',
  'Use 7-Zip instead of WinRAR - it\'s free and faster.',
  'qBittorrent is the best torrent client - no ads.',
  'Use VLC for videos - it plays everything.',
  'ShareX is the best screenshot tool - free and powerful.',
  'Use Firefox or Brave for privacy - Chrome uses tons of RAM.',
  'uBlock Origin is essential for blocking ads.',
  'Use Steam library folders to install games on multiple drives.',
  'Epic Games launcher is a resource hog - close it after launching games.',
  'GOG Galaxy can combine all your game libraries in one place.',
  'Use DS4Windows for PlayStation controllers on PC.',
  'InputMapper works for older controllers.',
  'ReShade can improve graphics but may get you banned in multiplayer.',
  'Medal.tv and Medal Clip are easy for saving gameplay highlights.',
  'Use Shadowplay for NVIDIA or ReLive for AMD instant replays.',
  'Discord has screen share but it can reduce FPS - use carefully.',
  'Use Parsec for low-latency remote gaming.',
  'Moonlight and Sunshine work great for NVIDIA GameStream.',
  'AutoHotkey lets you create custom macros (check game ToS first).',
  'Use Borderless Gaming to force games into borderless window.',

  // Storage & Files (261-280)
  'Keep at least 15% of your SSD free for optimal performance.',
  'TRIM is enabled by default on Windows for SSDs - don\'t disable it.',
  'Use Windows Storage Sense to auto-delete temp files.',
  'Move your Documents and Downloads folders to a secondary drive.',
  'Uninstall games you don\'t play to free up space.',
  'Use WinDirStat to visualize what\'s taking up disk space.',
  'Delete shader caches from old games you\'ve uninstalled.',
  'Empty your recycle bin regularly - it still uses space.',
  'Compress old files with 7-Zip to save space.',
  'Cloud storage is great for backups but slow for games.',
  'Use symbolic links to move game files without breaking them.',
  'Clean temp folders manually: %temp% and C:\\Windows\\Temp.',
  'Disable hibernation file if you never use it - saves GBs.',
  'Old Windows Update files can be deleted with Disk Cleanup.',
  'Disable System Restore on game drives to save space.',
  'Use external drives for archiving old games.',
  'M.2 drives run hot - some need heatsinks for sustained performance.',
  'SATA SSDs are still great - you won\'t notice the difference vs NVMe in games.',
  'Backup your saves before reinstalling games or Windows.',
  'Use Steam Cloud, but verify it worked before deleting local saves.',

  // Learning & Community (281-310)
  'Join gaming forums to learn tips from experienced players.',
  'Watch pro players to learn strategies and settings.',
  'Practice aim trainers like Aim Lab or Kovaak\'s daily.',
  'Record your gameplay to review mistakes.',
  'Warmup for 10-15 minutes before competitive matches.',
  'Play casual modes to try new strategies without pressure.',
  'Don\'t rage quit - staying calm improves performance.',
  'Take breaks between matches to stay focused.',
  'Hydrate regularly - dehydration hurts reaction time.',
  'Get 7-8 hours of sleep for peak gaming performance.',
  'Use voice comms effectively - callouts matter.',
  'Mute toxic players immediately - mental health matters.',
  'Support your teammates - positive attitudes win games.',
  'Learn from losses - every death is a lesson.',
  'Stretch your hands and wrists to prevent RSI.',
  'Check OptiPlay news for esports updates and tournaments.',
  'Follow hardware YouTube channels like Gamers Nexus.',
  'LTT is entertaining but Gamers Nexus is more technical.',
  'Hardware Unboxed has excellent monitor reviews.',
  'Tom\'s Hardware and AnandTech have in-depth articles.',
  'Reddit communities like r/buildapc are helpful.',
  'Check r/buildapcsales for deals on components.',
  'Use PCPartPicker for build planning and compatibility.',
  'Watch before-you-buy reviews before upgrading.',
  'Join OptiPlay\'s forum to discuss builds and tips.',
  'Share your benchmark results on OptiPlay.',
  'Vote in OptiPlay\'s daily polls.',
  'Contribute to OptiPlay with tips and guides.',
  'Stay updated on driver releases from NVIDIA and AMD.',
  'Follow tech Twitter for breaking news on new GPUs and CPUs.',

  // Security & Privacy (311-330)
  'Use strong unique passwords for every account.',
  'Enable 2FA on Steam, Epic, and all gaming accounts.',
  'Never click suspicious links - phishing is common.',
  'Don\'t download cheats - they often contain malware.',
  'Keep Windows and games updated for security patches.',
  'Use a password manager like Bitwarden or 1Password.',
  'Don\'t share your account - it violates ToS and risks bans.',
  'Be careful with free game key sites - scams are common.',
  'Official resellers: Steam, GOG, Humble, Fanatical.',
  'G2A and similar gray market sites are risky.',
  'Use PayPal for extra purchase protection.',
  'Check reviews before buying from unknown sites.',
  'Discord scams are common - verify links carefully.',
  'Never enter credentials on untrusted websites.',
  'Use email aliases to reduce spam.',
  'Disable telemetry in Windows if privacy matters to you.',
  'Use a VPN on public WiFi for security.',
  'Encrypt sensitive files with VeraCrypt.',
  'Backup important data to external drives regularly.',
  'Test your backups - corrupted backups are useless.',

  // Troubleshooting (331-365)
  'Game crashing? Verify game files in Steam or Epic.',
  'Update DirectX and Visual C++ Redistributables.',
  'Low FPS? Check if your GPU drivers are up to date.',
  'Stuttering? Check for thermal throttling with HWInfo.',
  'Black screens? Try different cables or ports.',
  'No display? Reseat your GPU and cables.',
  'PC won\'t POST? Check RAM is seated properly.',
  'Random crashes? Test RAM with MemTest86.',
  'Blue screens? Note the error code and Google it.',
  'Overheating? Reapply thermal paste and clean fans.',
  'Artifacts on screen? Your GPU might be dying.',
  'Coil whine? Normal but annoying - try different power settings.',
  'PC randomly restarts? Check PSU and temperatures.',
  'Games freezing? Close background apps and update drivers.',
  'Audio crackling? Update audio drivers or disable enhancements.',
  'Controller not working? Try different USB ports.',
  'Steam downloads slow? Change download region in settings.',
  'High ping only in one game? Check server status.',
  'FPS drops after Windows update? Roll back or wait for fix.',
  'GPU fans not spinning? They might be in idle mode below 60°C.',
  'PC loud? Clean dust and adjust fan curves.',
  'Monitor flickering? Try different refresh rate or cable.',
  'Games look washed out? Check NVIDIA/AMD color settings.',
  'Input lag on TV? Enable Game Mode in TV settings.',
  'Windows slow after update? Give it 24 hours to finish indexing.',
  'Disk at 100%? Disable Superfetch and check for malware.',
  'High CPU usage? Check Task Manager for background processes.',
  'Low GPU usage in game? Might be a CPU bottleneck.',
  'FPS capped at 60? Disable V-Sync and check frame limiters.',
  'Mouse feels sluggish? Disable pointer precision in Windows.',
  'Game won\'t launch? Run as administrator or update Visual C++.',
  'Cannot uninstall program? Use Revo Uninstaller.',
  'PC slow on startup? Disable startup programs in Task Manager.',
  'Cannot delete file? Use Unlocker tool to force delete.',
  'Lost game save? Check Steam Cloud or Documents folder.',
];

export default function DailyTip(){
  const tip = useMemo(() => {
    const day = Math.floor(Date.now() / (24*60*60*1000));
    return tips[day % tips.length];
  }, []);

  return (
    <div className="rounded-xl bg-[#0b0b10] border border-white/10 p-4">
      <h3 className="font-semibold mb-2">Daily Tip</h3>
      <p className="text-sm text-gray-300">{tip}</p>
    </div>
  );
}

